### ISSUE TITLE
Camera doesn't work.

### ISSUE THREAD

**Issue by kaitobaka** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#1]
message "USB Accessory Needs Power Connect" always show up and camera doesn't work but it show correctly on System Information.

also other USB port. when I plug USB wifi in. It show "USB Accessory Needs Power Connect" too

**Comment by THEDEVIOUS1** [comment]
should be good to go now...just replace the entire clover folder OR more specifically delete ssdt-usbx.aml  (NOT ssdt-ec-usbx.aml) from apci/patched and add "ssdt-uiac.aml" to the same folder

**Comment by kaitobaka** [comment]
it's work!! 

only problem now is Power Management. When i plug in or pull charger out it delay to change power state between battery<>plug.

one more question, can HiDPI mode run in 1.5x instead of 2x scaling?

**Comment by THEDEVIOUS1** [comment]
just so u know...i am working on a resolution solution but no success so far. i also see that u post on facebook (i dont but i like to lurk...lol) but if u want to help keep that thread updated/point them to fixes for problems i would appreciate it...ive added easier ways to change rotation & create the installer(olarila). also...added other operating systems that ive tried with links

**Comment by b00t0x** [comment]
@THEDEVIOUS1 The picture you placed on README.md is 1280x800@2x size, how did you configure it?

**Comment by THEDEVIOUS1** [comment]
my apologies...was too lazy to take a real one so stole that from a different device. lol...ironically it was also wrong because if u look at the pic it reports a screen size of 12 inches as opposed to our actual 8. will try to fix this image now to cut down on confusion...thx

**Comment by b00t0x** [comment]
I have difficulty in using custom resolution too. If I found the solution I'll inform you.
