### ISSUE TITLE
Bluetooth detects devices but refuses to connect

### ISSUE THREAD

**Issue by juanjsebgarcia** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#10]
I'm having an issue where my Minibook detects the Bluetooth devices around it, but any attempt to pair results in an automatic "connected" state and no actual connection. Quite frustrating!

Let me know how and if I can get any data that may be useful for debugging. I'm new to this scene.

Thanks for all your great work on this repo! Cannot wait to get touchscreen support :)

**Comment by kostaskas** [comment]
Mine connects for some seconds and disconnect. When turning on USB tethering for internet sharing on my phone, minibook stays connected but no internet. 

But can send files no my phone, receiving from phone isn't accepted by minibook

**Comment by THEDEVIOUS1** [comment]
@juanjsebgarcia replace your entire clover folder with this one...report back with results please. as an added bonus...touchscreen should be good to go in this one
[CLOVER6a.zip](https://github.com/THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH/files/4076913/CLOVER6a.zip)

**Comment by juanjsebgarcia** [comment]
Thanks @THEDEVIOUS1 

Can confirm touchscreen works great with finger touches (less so with pen, but thats expected), but no luck with Bluetooth.

I recorded the issue
https://www.dropbox.com/s/tg9oicezu7vti7z/Screen%20Recording%202020-01-17%20at%2006.08.37.mov?dl=0

**Comment by THEDEVIOUS1** [comment]
heres one more if u wanna try again...it may not help much but clear cache and erase nvram if u can
[CLOVER6.zip](https://github.com/THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH/files/4077207/CLOVER6.zip)

**Comment by juanjsebgarcia** [comment]
Unfortunately no luck with that one either, thanks for trying though!

**Comment by THEDEVIOUS1** [comment]
one more thing...try a warm boot from windows/linux or in other words restart (dont shutdown) directly from of those into macos

**Comment by hatran0884** [comment]
in my case, I am only able to connect with Apple Magic Mouse without issue. other than that, no other brands works. you can try with a Magic Mouse and feedback your result

**Comment by juanjsebgarcia** [comment]
The warm boot fixed the Fan issue from the other ticket, but BT continues to nerp :(

**Comment by juanjsebgarcia** [comment]
@hatran0884 I dont have a Magic Mouse but I tried an older Apple keyboard I had at home and it connected successfully straight away. Weird!

**Comment by THEDEVIOUS1** [comment]
try this....preferably with the last clover folder i uploaded

1. Turn off Bluetooth
2.  Delete com.apple.Bluetooth.plist from /Library/Preferences
3. Delete files named com.apple.Bluetooth.plist.somehexuuidstuff from ~/Library/Preferences (note that this is the user preference folder, not the system one)
4. Reboot system
5. Turn on Bluetooth

**Comment by juanjsebgarcia** [comment]
I'm on vacation for two weeks, but will be sure to come back and try this ASAP. Keen to have it working!

**Comment by balopez83** [comment]
Issue should be resolved with new EFI release coming this week. If you continue to have issues after testing new release please re-open or create a new ticket.

**Comment by balopez83** [comment]
I wanted to add some information on this. 

I have discovered some information that has led me to believe that the ongoing issues with Bluetooth may be related to interference issues between the Intel WIFI card and the Bluetooth chip. 

The only true solution likely won't occur without either fully disabling the WIFI card which would disable the now working Intel WIFI or waiting for the Intel WIFI project to mature where its likely that the interference issue will begin to resolve itself once they add additional frequencies to the driver. Once new frequencies are added, the driver should select alternative frequencies to reduce interference which will allow Bluetooth to become more stable. There is currently no ETA on additional frequency support as that project is managed by another group.
