### ISSUE TITLE
FileVault enable

### ISSUE THREAD

**Issue by kostaskas** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#11]
I have tried to enable **Filevault** to check if it's working. After that, when I choose **Preboot FileVault** entry on Clover, I get a black screen that should ask for password there in order to boot. Keyboard wasn't recognised to enter (invisibly...) the password there, so I added the attached files, that way keyboard is recognised, you still get the blank screen but you can enter password invisibly to proceed to boot.

[AppleUiSupport.zip](https://github.com/THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH/files/4971505/AppleUiSupport.zip)
[AppleGenericInput.zip](https://github.com/THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH/files/4971506/AppleGenericInput.zip)

**Comment by balopez83** [comment]
FileVault enabled as of release 0.2.4
