### ISSUE TITLE
modified bios not working

### ISSUE THREAD

**Issue by b00t0x** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#2]
Flashing the modified bios did not expand the menu.
It seems to be same as the original bios from [here](https://forum.chuwi.com/t/topic/3282).
```
$ md5 ./共用BIOS/Bios2019-09-28/bios.bin ./CHUWI-MINIBOOK-HACKINTOSH/Bios2019-09-28Mod/Bios.bin
MD5 (./共用BIOS/Bios2019-09-28/bios.bin) = b7e735795622ffb43bb7212b33fe4aaa
MD5 (./CHUWI-MINIBOOK-HACKINTOSH/Bios2019-09-28Mod/Bios.bin) = b7e735795622ffb43bb7212b33fe4aaa
```

**Comment by THEDEVIOUS1** [comment]
made a mistake and left the original in the folder but just replaced it with the proper version.,..thanks for letting me know

**Comment by kostaskas** [comment]
On Chuwi forum you will find the way to patch stock latest BIOS. Because as I undrestood, the patched one from bios-mod site, has lower cpu power to avoid heating...

**Comment by lazd** [comment]
@kostaskas can you link to the relevant thread? 

Also, that patched BIOS sounds like a great thing to contribute to the repository once applied and tested!

**Comment by kostaskas** [comment]
> @kostaskas can you link to the relevant thread?
> 
> Also, that patched BIOS sounds like a great thing to contribute to the repository once applied and tested!

Of course, that's the link [here](https://forum.chuwi.com/t/topic/3113/2). There is info how to unlock yours or just flash the one provided there. I unlocked mine because didn't want to lose info for my minibook, like Windows 10 Home serial number.
After unlocking, the main think that you have the freedom to make adjustments, like the one for 1080p video on Hackintosh

**Comment by lazd** [comment]
Ah interesting. I've already flashed the BIOS included in this repo, so it sounds like I lost my serial number, eh?

**Comment by kostaskas** [comment]
> Ah interesting. I've already flashed the BIOS included in this repo, so it sounds like I lost my serial number, eh?

Maybe yes, you lost it. But, you can buy one cheaply on the internet and upgrade to Win10 Pro..
