### ISSUE TITLE
Bluetooth and Battery Issue - Improper Install?

### ISSUE THREAD

**Issue by thetomcraig** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#22]
Hey guys, I've found that my minibook's bluetooth does not seem work, and something is up with the battery as well; it will say "100%" for a long time until it clearly hits 0% and dies suddenly.

I'm new to this EFI stuff so I could have simply not done the install correctly... One thing I found odd: after the initial install of macOS, I used Clover Configurator to mount the internal EFI partition, BUT it appeared to be completely empty... I dropped the "EFI" folder from "EFI-Clover" in there, but I'm not sure why it was empty to begin with.  Step 5 of your guide reads "...mount your EFI partition and copy over your Clover or OpenCore folders along with your BOOT folder found in the EFI folder on your install usb; you must copy/overwrite the same folders on the same partition located on your SSD." which implies the EFI partition should already be populate with some files/folders.

Is that right? Any idea why it would be empty?  Did I eff this up?

**Comment by balopez83** [comment]
Hi @thetomcraig , So you are not doing anything completely wrong, basically you have a few things going on:
 1. Bluetooth has known issues with the MiniBook in macOS and other similar devices using the same chipset in macOS. Unfortunately, this is likely hardware related or possibly limitations with the bluetooth kext but either way is not something we can resolve. In most cases some Apple devices will still usually work over bluetooth but have a very short range and unfortunately can be unreliable. 
2. Your battery issue is also known. The OEM battery included in the MiniBook is defective. There are countless threads now that discuss it and the recommendation is to replace it with an aftermarket battery. Check the facebook forums for the MiniBook and you will find links to the replacement batteries that can be ordered from AliExpress. Now that your battery is not showing the correct percentage it is only a matter of time before the battery begins to swell which is dangerous. You can delay the inevitable by opening the device, unplugging the battery and then plugging it back in. This is only a temp solution for getting the battery percentage back. 
3. Depending on which install method you chose and if you completely formatted your SSD you actually would have an empty EFI partition. In some cases macOS will create an EFI folder within the EFI partition and drop an Apple folder within that though its not always the case. If you had simply kept your Windows install, created a partition for macOS and installed there then you should have a Windows EFI folder. 

On another note, you mentioned using the Clover EFI and not OpenCore. I know that Clover can seem easier to use but I would recommend using the OpenCore EFI instead. Keep in mind that we will no longer be supporting Clover as it does not work properly in Big Sur despite some support finally being added by Clover's developers. Additionally, OpenCore has better overall support and enables many more features such as native WiFi among other things that isn't supported at this time if ever with Clover.

Hope this helps

**Comment by thetomcraig** [comment]
@balopez83 thanks for that detail, very helpful! I'll look into the battery issue and doing an OpenCore install.  Fwiw I have had some success using a bluetooth USB dongle, sounds like this may be the best way to go ¯\_(ツ)_/¯.
