### ISSUE TITLE
sleep mode issue

### ISSUE THREAD

**Issue by hatran0884** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#7]
Hi

I have another issue with the sleep mode. initially it works quite well but after a while, the sleep mode works unstably. right after it goes to sleep, it wakes up.
wake reason reported is : PWRB GLAN XHCI
if I restart the system, sleep mode works well again but still in just a few hours, sometimes in a few days.
anyone having the same issue ? and what might be the root cause ? 
thanks

**Comment by THEDEVIOUS1** [comment]
balopez did the usb work but im not sure if he will chime in because his minibook is broken....with that said from what im aware of the xhci refers to the ports so maybe something connected(possibly internally) is disturbing the systems rest and this may actually be tied to issue 5. I'll admit im totally guessing with the rest of this though...think GLAN is ethernet so if youre using the hacked bios u can see if theres a wake on lan to disable or possibly power nap in the pref plane but if u just happen to be using a usb ethernet adapter that i would almost definitely be the culprit to me

**Comment by hatran0884** [comment]
does your minibook encounter this issue? actually I am using TP Link wireless adapter plugged into USB 2 port which might be the cause ?
could you help to check if the hacked bios has an option of disabling the wake on LAN ? 
I heard from instruction that there is possibility of windows key being deleted which prevents me from flashing it. so if there is an option of Wake on LAN there, I can consider to flash it.

**Comment by THEDEVIOUS1** [comment]
to be totally honest i dont use macos enough to know but the times ive seen it fall asleep i havent ever had it awaken on its own...if i were u i would go to the energy saver section of the  preference panes and check/uncheck powernap/wake for wifi or other related settings first (possibly the network and/or wiresless usb app settings also)

**Comment by balopez83** [comment]
Hi @hatran0884 , I don’t have my computer to test anymore but I also wasn’t experiencing this issue but I think @THEDEVIOUS1 is correct. Check that you don’t have the checkbox checked to allow periodic checks for emails, notifications, etc. With the current setup powernap won’t work and likely won’t ever as it requires an internal apple standard WiFi card to work properly. 

If that doesn’t fix it my next guess would be you need to fix your hibernation/sleep settings and that can be done easily with Hackintool. In the power tab of hackintool you will see your current power settings and likely one or more lines is highlighted red. At the bottom there should be a gear and wrench icon and when clicked it will correct your power settings after which should those lines will change color. 

With any luck that should prevent your computer from powering back up out of sleep. If that fixes it please let us know so we can close the issue, thanks.

**Comment by hatran0884** [comment]
> Hi @hatran0884 , I don’t have my computer to test anymore but I also wasn’t experiencing this issue but I think @THEDEVIOUS1 is correct. Check that you don’t have the checkbox checked to allow periodic checks for emails, notifications, etc. With the current setup powernap won’t work and likely won’t ever as it requires an internal apple standard WiFi card to work properly.
> 
> If that doesn’t fix it my next guess would be you need to fix your hibernation/sleep settings and that can be done easily with Hackintool. In the power tab of hackintool you will see your current power settings and likely one or more lines is highlighted red. At the bottom there should be a gear and wrench icon and when clicked it will correct your power settings after which should those lines will change color.
> 
> With any luck that should prevent your computer from powering back up out of sleep. If that fixes it please let us know so we can close the issue, thanks.

hi @balopez83 yes, I have checked and found 02 red lines: hibernatemode and proximity. so followed what you suggested, both lines changed to green. I am testing to see if it fixes this issue. will keep you posted with the result soon. thanks you guys @THEDEVIOUS1  @balopez83 for your prompt support.

**Comment by hatran0884** [comment]
Hi @balopez83 unfortunately the issue still persists. This time it occurred after 02 days which is pretty longer than usually. It is hard for me to understand why it occurs, i only surf internet via Safari without anything else. Once this issue happens if i shut it down, instead of shutdown, it will restart, then i press the power button to shut it down it restarts again. I have to press power button one more time to shut it down completely. Pretty strange.

**Comment by balopez83** [comment]
@hatran0884 , I’m not entirely sure why it’s causing an issue still but glad it’s better. I likely won’t be able to look into it further until I get my computer replaced and that will be a while as it has to be sent to China for repair. 

That said open clover configurator and check that the “fix shutdown” check box is checked. If I remember the github config file does not have it checked by default and that should fix your restart issue. If it’s already checked try unchecking and then rechecking, saving and seeing if that fixes the restart issue. 

Is your macOS install on an internal SATA ssd, NVMe ssd, or from an Usb drive? If you are booting from a USB that could be related to your sleep issue but I’m guessing that you prob have it installed on an internal. 

One more question, are using a kext driver for your WiFi installed in your EFI or driver installed to macOS directly in either L/E or S/L/E? I’m thinking there may be some issues on the minibook with the current state of setup with drivers installed in the EFI rather than L/E or S/L/E. If you have it installed in the EFI I would suggest trying installing to L/E and deleting from the EFI and see if that resolves your issue.

**Comment by hatran0884** [comment]
Yes, the fix shutdown is unchecked, so i have checked it and it seems to be okay now, no more restart upon shutdown.
I installed the wifi kexts into EFI, so i have installed them into L/E as your susgestion. Also deleted them from EFI. Still testing, hope it can resolve this issue.
By the way, minibook seems to be a perfect hackintosh device  with very small size beside the gpd p2 max. Hopefully once you got yours from repair, keep up your great works to resolve the remaining issues: higher resolution, usb 3 port and sd card reader. Thanks!

**Comment by balopez83** [comment]
Great to hear that seems to have fixed it @hatran0884 . Report back in a few days to let us know if it’s still fixed and we will close this issue.

**Comment by hatran0884** [comment]
> Great to hear that seems to have fixed it @hatran0884 . Report back in a few days to let us know if it’s still fixed and we will close this issue.

Hi @balopez83 the issue of instant wake still persists. Last night, i put it to sleep mode well and went to sleep, but this time, it woke itself up in the mid night so i found it awake in the morning. Cannot understand what is wrong?

**Comment by balopez83** [comment]
@hatran0884 hmm, so did the computer stay asleep longer before or after the move of the kexts to L/E or was there no real difference?

Try uninstalling the WiFi drivers and wifi manager and use this one:  https://github.com/chris1111/Wireless-USB-Adapter/blob/master/README.md (good for both Mojave or Catalina same guy who made the drivers you have installed but different method)

Let me know if this fixes the issue? If this doesn’t work please also try removing the WiFi Usb and putting the computer to sleep and let me know if the issue happens while its removed. @THEDEVIOUS1 is working on some stuff right now with the hopes it will also resolve this issue as well

**Comment by hatran0884** [comment]
> @hatran0884 hmm, so did the computer stay asleep longer before or after the move of the kexts to L/E or was there no real difference?
> 
> Try uninstalling the WiFi drivers and wifi manager and use this one: https://github.com/chris1111/Wireless-USB-Adapter/blob/master/README.md (good for both Mojave or Catalina same guy who made the drivers you have installed but different method)
> 
> Let me know if this fixes the issue? If this doesn’t work please also try removing the WiFi Usb and putting the computer to sleep and let me know if the issue happens while its removed. @THEDEVIOUS1 is working on some stuff right now with the hopes it will also resolve this issue as well

hi @balopez83 it seems moving the kexts to L/E made no difference. yesterday, the issue occurred in just a few times of sleeps in a few hours. 

I have just installed the wifi adapter by the new way. still testing now. 
but I also suspect the bluetooth, because when the issue happened, I tried to boot into windows and found the bluetooth driver giving an error of STATUS POWER FAILURE, if I close the lid and reopen it, the bluetooth issue runs away. let me test it more.
by the way, I found that the hackintools says that there are some updated kexts available, so is it okay to update all the kexts in EFI ?

**Comment by hatran0884** [comment]
by the way, I have also had to reinstall the EC because the battery indicator in Windows did not work properly, stuck at 100% for hours and shut down immediately at 20-25%. reinstalling the Embedded controller resolved this issue, but I am not sure it might effect the DSDT-EC. just want to give you one more clue/

**Comment by hatran0884** [comment]
Hi @balopez83 quick update, i tried to install the wifi kext based on the new method, still no improvement. I have also uninstalled all the wifi drivers and unplugged all devices from the 2 usb ports and tested, still didn’t work. So i am really expecting you guys can resolve it on your minibook.

**Comment by hatran0884** [comment]
hi @balopez83 any update on this issue? I have tried to edit the DSDT to disable wake up by GLAN and wake up by USB, the issue still there. 
what else I can do now ?

**Comment by balopez83** [comment]
Hi @hatran0884 , I wouldn’t recommend attempting to edit the dsdt to solve the wake issue as it may cause other issues. Unfortunately without my computer I will be unable to find a solution for this issue and so I would recommend shutting down instead or disconnecting your WiFi prior to sleeping if that helps until we can find a resolution. 

I saw that in the chuwi Facebook group that this may be a bigger issue affecting users on the windows side of things which may be indicating an issue requiring chuwi to release another bios or ec update. When I get my computer back I’ll dig in further but unfortunately I won’t have an answer for this issue until then.

**Comment by hatran0884** [comment]
> Hi @hatran0884 , I wouldn’t recommend attempting to edit the dsdt to solve the wake issue as it may cause other issues. Unfortunately without my computer I will be unable to find a solution for this issue and so I would recommend shutting down instead or disconnecting your WiFi prior to sleeping if that helps until we can find a resolution.
> 
> I saw that in the chuwi Facebook group that this may be a bigger issue affecting users on the windows side of things which may be indicating an issue requiring chuwi to release another bios or ec update. When I get my computer back I’ll dig in further but unfortunately I won’t have an answer for this issue until then.

i am also a member of that FB group and aware of that post, you are right, it is very likely to be due to the minibook itself, i am checking in Windows to see if it wakes up sometime.
i am very regretful to have the issue of wakeup and battery EC in this mini PC, without it, it would be a perfect hackintosh ever.

**Comment by THEDEVIOUS1** [comment]
totally unrelated to this issue...if u want to help test the touchscreen then come join us in [this gitter room](https://gitter.im/lazd/VoodooI2CGoodix)

**Comment by hatran0884** [comment]
@balopez83 quick update, I have edited the DSDT to remove the _PWR blocks under GLAN, XDCI and XHC. now the wake up reason of PWRB GLAN XHCI has gone and replaced by a new reason: PWRB HDEF which I have no idea what it is. but at least so far the instant wakeup has not happened again, will keep observing to see if it resolves completely

**Comment by hatran0884** [comment]
@balopez83 this sleep issue also has been fixed by removing the PRW methods in XHC, GLAN, XDCI and HDAS in DSDT

**Comment by balopez83** [comment]
This issue continues to be a problem but is being worked on. Please update to Release 0.1.0 to be posted this week and let me know if you still have problems with sleep. If you have determined and solved your sleep issue please report back so we can integrate any fixes into the next release.

**Comment by balopez83** [comment]
Sleep issue will be resolved in release 0.2.2 and later versions which will be posted in within the next few days. Finalizing and cleaning up code prior to uploading.
