### ISSUE TITLE
Fans do not work from cold boot

### ISSUE THREAD

**Issue by lazd** [THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH#9]
Fans work if you warm boot from Windows, changing speed according to temperature as one would expect, keeping CPU temps as low as 60°.

If you cold boot, fans stay at their lowest speed and CPU temps can get up to 95°C.

**Comment by kostaskas** [comment]
Or fans stay completely off if you have modded EC 
hehe

**Comment by juanjsebgarcia** [comment]
Can confirm this is an issue for me too, the machine will get very hot over a session and the fan will not ramp up to compensate. This seems like rather a critical issue.

I have tried using Macs Fan Control but of course it doesn't detect the fan :/

Edit: Warm reboot from a Ubuntu USB live distro does fix it, need to test if this is then reset by a shutdown or if it survives suspends.

**Comment by lazd** [comment]
Note that if you sleep or restart after a warm boot, fans will continue to work.

**Comment by balopez83** [comment]
Resolved with Release 0.1.0 to be posted this week. If you continue to have issues after completely replacing your EFI with this release please either re-open or create a new ticket.
